MethodLength:
  Max: 30
HashSyntax:
  Enabled: false
AvoidGlobalVars:
  Enabled: false
RescueModifier:
  Enabled: false
RedundantReturn:
  Enabled: false
AsciiComments:
  Enabled: false
AssignmentInCondition:
  Enabled: false
Documentation:
  Enabled: false
